name: Indexer

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: git config
      run: | 
        git config --local user.email "zeta3@numberdb.org"
        git config --local user.name "zeta3[bot]"
    - name: Install python packages
      run: |
        pip3 install wheel
        pip3 install gitpython
    - name: Run indexer.py
      run: |
        python3 indexer/indexer.py
    #We already commit in indexer.py
    #- name: Commit files
    #  run: |
    #    git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
